version: '3.8'
services:
  mysql-8:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Dhaka'
    env_file:
      - ./.env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+06:00']
    volumes:
      - ./data/mysql-8:/var/lib/mysql
      - ./config/mysql-8:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '0.25'
          memory: 200M

  percona-8:
    image: amd64/percona:8.0
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Dhaka'
    env_file:
      - ./.env
    volumes:
      - ./data/percona-8:/var/lib/mysql
      - ./config/percona-8:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '0.25'
          memory: 200M
      
  postgres-15:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'Asia/Dhaka'
      PGTZ: 'GMT+6'
    volumes:
      - ./data/postgres-15:/var/lib/postgresql/data
      - ./config/postgres-15:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '0.25'
          memory: 200M

# https://learn.microsoft.com/en-us/azure/azure-sql-edge/disconnected-deployment
# https://github.com/mcmoe/mssqldocker
  mssql-2022:
    image: mcr.microsoft.com/azure-sql-edge
    command: /opt/mssql/bin/sqlservr
    ports:
      - 1433:1433
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ${DB_ROOT_PASSWORD}
      MSSQL_USER: ${DB_USER}
      MSSQL_PASSWORD: ${DB_PASSWORD}
      MSSQL_DATABASE: ${DB_NAME}
      MSSQL_SLEEP: 7
    env_file:
      - ./.env
    stdin_open: true
    volumes:
      - ./data/mssql-2022:/var/opt/mssql
      - ./config/mssql-2022:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '0.25'
          memory: 200M
# https://stackoverflow.com/questions/71776934/initialize-sql-server-database-in-docker-container-without-sqlcmd
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    platform: linux/amd64
    stdin_open: true
    environment:
        MSSQL_SA_PASSWORD: ${DB_ROOT_PASSWORD}
        MSSQL_DATABASE: ${DB_NAME}
        MSSQL_BACKUP: "/opt/mssql/data.bak"
    env_file:
      - ./.env
    # command: /bin/bash -c '/opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P SA_Passw0rd -d master -Q "SELECT version()"'
    volumes:
      - ./data/mssql-2022/data.bak:/opt/mssql/data.bak